import sys

from utils import estimate

theta0: float = 0
theta1: float = 0

def read_file(file: str):
    global theta0, theta1
    try:
        with open(file, "r") as f:
            line = f.readline()
        # Here, no exception should occur if the user has not modified the file generated by the program.
        # So a basic exception message is sufficient.
        [t0, t1] = line.split(',')
        theta0 = float(t0)
        theta1 = float(t1)
    except Exception as ex:
        print(f"Cannot read/parse the input file: {str(ex)}", file=sys.stderr)
        print(f'Using 0 as default value for theta0 and theta1. Run `python3 train.py` to train the model.', file=sys.stderr)
        theta0 = 0
        theta1 = 0

if __name__ == "__main__":
    window = False

    read_file(sys.argv[1] if len(sys.argv) >= 2 else 'output.csv')

    for line in sys.stdin:
        try:
            print(estimate(float(line.strip()), theta0, theta1))
        except ValueError as ex:
            print(str(ex))
